name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags

on:
  pull_request:
  push:
    branches: ['master']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          check-latest: true

      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Lint code
        run: sbt ++3.3.3 check

  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '17', '21']
        scala: ['3.3.3']
        platform: ['JVM', 'JS', 'Native']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Setup node
        uses: actions/setup-node@v4
        if: matrix.platform == 'JS'
        with:
          node-version: '22'
      - name: Run tests
        run: sbt ++${{ matrix.scala }}! test${{ matrix.platform }}

  ci:
    runs-on: ubuntu-24.04
    needs: [lint, test]
    steps:
      - name: Aggregate of lint, and all tests
        run: echo "ci passed"
